title: Yinghao Lu's Homepage
page-top-title: Yinghao Lu
top-section-bg-text: Data Science
home-subtitle: Yinghao Lu&ensp;|&ensp;陆英浩
copyright-text: '&copy; Yinghao Lu 2024-2024. All Rights Reserved.'
